config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :topics do
    resources :posts
  end
  root 'topics#index'
  get 'posts' => 'posts#index', as: :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  validates :name, :presence => true
  validates :content, :presence => true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  validates :name, length: { minimum:1 }
  accepts_nested_attributes_for :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :getting

  def index
    @post = @data.posts
    #@post1 = Post.where(:topic_id => @post)
  end

  def show
    @show = Topic.find(params[:id])
  end

  def new
    @new = Post.new
  end

  def create
    @create = @data.posts.build(gets)
    if @create.save
      redirect_to topic_posts_path
    end
  end

  def edit
    @edit = @data.posts.find(params[:id])
  end

  def update
    @update = Post.find(params[:id])
    if @update.update(get)
      redirect_to topic_post_path(@data)
    end
  end

  def destroy
    @destroy = Post.find(params[:id])
    @destroy.destroy
    redirect_to topic_posts_path(@data)
  end
  private
    def get
      params.require(:post).permit(:name, :content)
    end

    def getting
      @data = Topic.find(params[:topic_id])
    end

    def gets
      params.require(:post).permit(:name, :content, :topic_id)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topic = Topic.all
  end

  def show
    @show = Topic.find(params[:id])
  end

  def new
    @new = Topic.new
  end

  def create
    @create = Topic.new(get)
    if @create.save
      redirect_to topics_path
    else
      render :new
    end
  end

  def edit
    @edit = Topic.find(params[:id])
  end

  def update
    @update = Topic.find(params[:id])
    if @update.update(get)
      redirect_to topics_path
    else
      render :edit
    end
  end

  def destroy
    @destroy = Topic.find(params[:id])
    @destroy.destroy
    redirect_to topics_path
  end

  private
    def get
      params.require(:topic).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled14</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for [@data,@edit] do |i| %>
  <p>
    <%= i.label :name %>
    <%= i.text_field :name %>
  </p>
  <p>
    <%= i.label :content %>
    <%= i.text_area :content %>
  </p>
  <p>
    <%= i.submit 'Update' %>
  </p>
<% end %>

app/views/posts/index.html.erb
<table>

  <tr>
    <th><%= 'Name of the post' %></th>
    <th><%= 'Content' %></th>
  </tr>

<% @post.each do |i| %>
  <tr>
    <td><%= i.name %></td>
    <td><%= i.content %></td>
    <td><%= link_to 'Update',edit_topic_post_path(@data,i) %></td>
    <td><%= link_to "Delete", [@data, i], :data =>{:confirm=>"Are you sure?"}, :method=> :delete %></td>
  </tr>
    <% end %>
</table>

<p><%= link_to 'Add post',new_topic_post_path %></p>

app/views/posts/new.html.erb
<%= form_with(model:[@data,@new]) do |i| %>
  <p>
    <%= i.label :name %>
    <%= i.text_field :name %>
  </p>
  <p>
    <%= i.label :content %>
    <%= i.text_field :content %>
  </p>

  <p><%= i.submit 'Added' %></p>
<% end %>

app/views/posts/show.html.erb
<p>
  <%= @show.name %><br/>
</p>

app/views/topics/edit.html.erb
<%= form_for Topic.find(params[:id]) do |i| %>
  <p>
    <%= i.label :name %>
    <%= i.text_field :name %>
  </p>
  <p><%= i.submit 'Change' %></p>
<% end %>

app/views/topics/index.html.erb
<h1><center>Topics</center></h1>
<table>
  <tr>
    <th>Name of the Topic</th>
  </tr>
<% @topic.each do |i| %>
    <tr>
    <td><%= link_to i.name,i %></td>
      <td><%= link_to 'Show',topic_posts_path(i) %></td>
      <td><%= link_to 'Edit',edit_topic_path(i) %></td>
      <td><%= link_to 'Delete',i,:data=>{:confirm=>'Are you sure to delete'},:method=>:delete %></td>
    </tr>

<% end %>
</table>
<%= link_to 'Add', new_topic_path %>

app/views/topics/new.html.erb
<%= form_for Topic.new do |i| %>
  <p>
    <%= i.label :name %>
    <%= i.text_field :name %>
  </p>
  <p><%= i.submit 'Add new' %></p>
<% end %>

app/views/topics/show.html.erb
<h3><%= @show.name %></h3>